#!/usr/bin/bash



############# TEAM_DARWIN REPOSITORY #########

#clone the repository
git clone https://github.com/Khalid-Fahd/Hackbio-Team-Darwin

echo 'Welcome to Team_Darwin Repository'


#open the Hackbio repo
cd Hackbio-Team-Darwin

#create a csv file with headers
echo 'Name,Email, Slack_Username, Biostack' > header.csv

#creating all files
for f in *
do
        python3 Python_SMB.py $f >script1.txt
        python3 Python_Khalid-Fahd.py $f >script2.txt
        python3 Python_Shalaka.py $f > script3.txt
        node  Js_Ishbah.js $f > script4.txt
        Rscript Rs_JananiSankar.r $f>script5.txt
        Rscript Rs_Farheen_Shah.r $f >script6.txt
        perl Perl_Shalaka.pl $f >script7.txt
        perl Perl_JEMINA-JOHN.pl $f > script8.txt
        #gcc C_Joyomonigho.c  $f
        #./a.out >script9.txt
        #gcc C_Samson.c $f
        #./a.out > script10.txt
        cat script1.txt script2.txt script3.txt script4.txt script5.txt script6.txt script7.txt script8.txt>allscripts.csv #script9.txt script10.txt
        cat header.csv allscripts.csv >mergedfiles.csv
done

