# -*- coding: utf-8 -*-
"""script
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1ife-YnxmXnsXCh4R51wW-OYuAwRG27vf
"""

print ('name:Samuel Mensah Baffoe' + 'email:samuelmensahbaffoe97@gmail.com' + 'discord_username:@SMB' + 'biostack:Transcriptomics')
